### ISSUE TITLE
Fighting bug

### ISSUE THREAD

**Issue by disorientedperson** [disorientedperson/python-adventure-game#23]
To see this problem, run `demo.py`, get into the house, go east, sw, then south, south again, and retreat. When you retreat, it asks you to fight again, but it crashes when you try to. Retreating should mean you are _avoiding_ the fighting.

**Comment by DaVinci789** [comment]
I cannot get it to crash

**Comment by disorientedperson** [comment]
@DaVinci789 When you successfully kill an enemy in this situation, it crashes.
```
You run towards the amazing riches...without noticing the giant hole at your feet.

You are in a dank, dirty pit. You don't know why you are here instead of being on a mountain of gold and jewels.

There is an exit north.
There is an exit south.

> s
You are in a featureless dark tunnel.

Black Pit is to the north.
Dead End is to the south.

There are 4 orcs here
What do you want to do?
1 Attack
2 Retreat
#2
You cowardly run away.
Your score was decreased by 1.
You are in Black Pit.

What do you want to do?
1 Attack
2 Retreat
#1
Choose your weapon.
fist: 10 power
sword: 138 power
Weapon: sword
The orc has been defeated!
Your score was increased by 1.
Traceback (most recent call last):
  File "./demo.py", line 243, in <module>
    game.play()
  File "/home/pi/python-adventure-game/pag/game.py", line 57, in play
    result = getattr(player, action)(action, noun)
  File "/home/pi/python-adventure-game/pag/classes.py", line 287, in go
    fight_check()
  File "/home/pi/python-adventure-game/pag/classes.py", line 227, in fight_check
    self.location.creatures.remove(i)
ValueError: list.remove(x): x not in list
```

**Comment by DaVinci789** [comment]
How do you get the sword again

**Comment by disorientedperson** [comment]
@DaVinci789 instead of taking the long approach just put `Sword` in the items list for home and take it :man_shrugging:

**Comment by DaVinci789** [comment]
Ok, getting crash now

**Comment by disorientedperson** [comment]
Yay(?)

**Comment by DaVinci789** [comment]
I believe that this is because we are modifying the same list we are looping over.

**Comment by disorientedperson** [comment]
@DaVinci789 What do you mean?

**Comment by DaVinci789** [comment]
I believe I may be wrong.  On line 230, self.location.creatures.remove(i) is called; the same list we are iterating over.

**Comment by DaVinci789** [comment]
It may also be that they are all named the same

**Comment by disorientedperson** [comment]
I understand what you're saying now. I don't think that's the issue. What's happening is that when the player returns to the previous location, it detects that there is a creature to fight. However, the `location.give_info` function doesn't detect the creature in the location creature list. These functions are getting different results, which is _bewildering_. That's why the error mentions a failure to remove something; there is nothing to remove.

I need to use a debugger.

**Comment by disorientedperson** [comment]
Okay. It only happens when there are multiple baddies in the area.

**Comment by disorientedperson** [comment]
If you choose retreat for a second time it works fine.
